name: powerviews

configs:
  powerviews_pg__pg_hba.conf:
    file: ${PGHBACONF:-docker/configs/pg_hba.conf}
  linkaform.com.chained.crt:
    file: ${LINKAFORMCRT:-docker/configs/linkaform.com.chained.crt}

secrets:
  linkaform.com.key:
    file: ${LINKAFORMCRTKEY:-docker/secrets/linkaform.com.key}
  config.json:
    file: ${POWERVIEWSCONFIG:-docker/secrets/config.json}

services:
  postgres:
    image: postgres:15-alpine # XXX we are stuck at pg 15, need changes in role creation to handle pg>=16
    hostname: pv_psql
    restart: always
    configs:
      - source: powerviews_pg__pg_hba.conf
        target: /var/lib/postgresql/tmp/pg_hba.conf
      - source: linkaform.com.chained.crt
        target: /var/lib/postgresql/tmp/linkaform.com.chained.crt
    env_file: 
      # for POSTGRES_PASSWORD, POWERVIEWS_ADMINUSER_PASSWORD
      - docker/envs/powerviews_pg.env
    environment:
        - PGDATA=/var/lib/postgresql/15/docker
        - POSTGRES_INITDB_ARGS=--data-checksums -E UTF-8
        # custom dir for temp files during initialization
        - CONFIGTMP=/var/lib/postgresql/tmp
        # custom dir for additional auxiliary files (used during operation)
        - CONFIGAUX=${CONFIGEXTRA:-/var/lib/postgresql/conf}
        # where auxiliary sql files are inside container
        - POWERVIEWS_INIT_SQLDIR=/__docker-entrypoint-initdb.d/_pv
        - PAGER=less # nicer gnu less instead of alpine more
        - EDITRC=/dev/null # dont use ~/.editrc by default
        # if set and not null prepare this postgres instance for restoring an
        # existing database generated with pg_dumpall, implies:
        # * dont run setup_pg.sh
        # * 
        - FOR_RESTORE=${FOR_RESTORE:-}
    volumes:
      - type: bind
        bind:
          create_host_path: ${PGDATAORIGCREATE:-true}
        source: ${PGDATAORIG:-pgdata}
        target: /var/lib/postgresql/15/docker
      - type: bind
        bind:
          create_host_path: false
        source: ./pg_utils/setup_pg.sh
        target: /__docker-entrypoint-initdb.d/setup_pg.sh
      - type: bind
        bind:
          create_host_path: false
        source: ./sql
        target: /__docker-entrypoint-initdb.d/_pv
    shm_size: 256MB # postgresql caches
    secrets:
      - linkaform.com.key
    command: >
        postgres
        -c hba_file=${CONFIGAUX:-/var/lib/postgresql/conf}/pg_hba.conf
        -c log_min_duration_statement=1000
        -c log_destination=stderr
        -c log_parameter_max_length=1024
        -c ssl=on
        -c ssl_cert_file=${CONFIGAUX:-/var/lib/postgresql/conf}/linkaform.com.chained.crt
        -c ssl_key_file=${CONFIGAUX:-/var/lib/postgresql/conf}/linkaform.com.key
    entrypoint: |
      bash -c '
      set -e
      apk update
      apk add less strace
      # if not in restore mode allow initialization files to run
      if test "$$FOR_RESTORE"; then
        echo "+ In FOR_RESTORE mode" >&2
      else
        rmdir /docker-entrypoint-initdb.d
        ln -sf /__docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
      fi
      # config psql ux
      echo bind -v > /.editrc
      echo bind "^I" rl_complete >> /.editrc
      # copy tmp config to aux config
      # XXX needed specially because pg process dont likes permissions of
      # /run/secrets/* files and they cannot be changed, so we copy them with
      # right permissions
      (
       set -xe;
       mkdir -p "$$CONFIGAUX";
       install -o postgres -g postgres -m 0600 "$$CONFIGTMP"/* /run/secrets/* "$$CONFIGAUX"
      )
      exec docker-entrypoint.sh "$@"
      '

  powerengine:
    hostname: powerengine
    image: linkaform/powerengine:prod
    build:
       target: engine
    env_file:
        - docker/envs/powerengine.env
    command: powerengine
    secrets:
      - config.json
    healthcheck:
      test: /srv/powerviews/engine/healthcheck
      interval: 10s
      timeout: 5s
      retries: 5

  powerviews:
    hostname: powerviews
    image: linkaform/powerengine:prod
    build:
       target: api
    env_file:
        - docker/envs/powerengine.env
    command: powerviews
    secrets:
      - config.json
