#!/bin/sh

# normally you would call this script with -d argument to deploy in background
env \
	PGDATAORIGCREATE=false \
	PGDATAORIG=/zpool/powerviews_postgres \
	docker compose -f compose.yaml -f publish.yaml up "$@"
