version: '3.7'
volumes:
  postgres_data_1333:
  postgres_data_132:
  postgres_data_13:

networks:
  linkaform:
    external:
      name: linkaform

services:
  powerengine:
    hostname: powerengine
    container_name: powerengine
    image: linkaform/powerviews:latest
    build:
       context: ./
       dockerfile: Dockerfile
       target: develop
    #command: ["sleep", "infinity"]
    command: ["powerengine"]
    volumes:
        - ./:/srv/powerviews
    env_file:
        - ./.env
    depends_on:
        - postgres
    networks:
      linkaform:
    entrypoint: /srv/powerviews/utils/entrypoint.sh

  powerviews:
    hostname: powerviews
    container_name: powerviews
    image: linkaform/powerviews:latest
    build:
       context: ./
       dockerfile: Dockerfile
       target: develop
    #command: ["sleep", "infinity"]
    command: ["powerengine"]
    volumes:
        - ./:/srv/powerviews
    depends_on:
        - postgres
    networks:
      linkaform:
    ports:
      - "8080:8080"
    entrypoint: /srv/powerviews/utils/entrypoint.sh

  postgres:
    image:  postgres:13-alpine
    container_name: pv_psql
    #command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    hostname: psql
    env_file:
      - ./.psql
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data_13:/var/lib/postgresql/data
      - ./pg_utils:/docker-entrypoint-initdb.d
    networks:
      linkaform:
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "powerviews", "-U", "powerviews_admin"]
      interval: 5s
      retries: 5
    restart: always
