version: '3.7'

networks:
  linkaform:
    external:
      name: linkaform
volumes:
  postgres_data_13:

secrets:
  config.json:
    external: true

services:
  powerengine:
    hostname: powerengine
    image: linkaform/powerviews:latest
    command: ["powerengine"]
    env_file:
        - ./.env
    networks:
      linkaform:
    entrypoint: /srv/powerviews/utils/entrypoint.sh
    secrets:
      - config.json

  powerviews:
    hostname: powerviews
    image: linkaform/powerviews:latest
    command: ["powerviews"]
    env_file:
        - ./.env
    networks:
      linkaform:
    ports:
      - "8080:8080"
    entrypoint: /srv/powerviews/utils/entrypoint.sh
    secrets:
      - config.json

  pv_psql:
    image:  postgres:13-alpine
    #command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    hostname: pv_psql
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=linkaform2018infosync
        - POSTGRES_DB=postgres
        - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data_13:/var/lib/postgresql/data
      - ./pg_utils:/docker-entrypoint-initdb.d
    networks:
      linkaform:
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "powerviews", "-U", "powerviews_admin"]
      interval: 5s
      retries: 5
