# Stage 1: The development stage:

FROM postgres:13-alpine AS develop

MAINTAINER LinkaForm



RUN echo "host   powerviews   +powerviews_users  0.0.0.0/0       md5" >> /var/lib/postgresql/data/pg_hba.conf
RUN echo "host   powerviews    powerviews_admin  172.16.0.0/16   md5" >> /var/lib/postgresql/data/pg_hba.conf
