drop view if exists myview;
select createpview('pv_1259.tbl3'::regclass, 'myview',
    '[
      { "folio": "text" },
      { "division": "text" },
      { "pryecto": "text" },
      { "estatus": "text" },
      { "subtotal": "money" },
      { "iva": "money" },
      { "retencion": "money" },
      { "total": "money" },
      { "estatus_factura": "text" },
      { "departamente": "array_text" },
      { "departamente": "array_text" },
      { "oc_folio": "text" },
      { "oc_importe": "array_money" },
      { "oc_importe": "array_money" },
      { "oc_importe": "array_money" },
      { "pdf": "pv_doc" },
      { "pdf": "pv_doc" },
      { "xml": "pv_doc" },
      { "xml": "pv_doc" },
      { "b3b": "pv_doc" }
    ]',
    '[
      { "folio": "text" },
      { "division": "text" },
      { "pryecto": "text" },
      { "estatus": "text" },
      { "subtotal": "money" },
      { "iva": "money" },
      { "retencion": "money" },
      { "total": "money" },
      { "estatus_factura": "text" },
      { "departamento_1": "text__0" },
      { "departamento_2": "text__1" },
      { "oc_folio": "text" },
      { "oc_importe_1": "money__0" },
      { "oc_importe_2": "money__1" },
      { "oc_importe_3": "money__2" },
      { "pdf": "pv_doc__file_name" },
      { "pdf_url": "doc__file_url" },
      { "xml": "pv_doc__file_name" },
      { "xml_url": "doc__file_url" },
      { "b3b": "pv_doc__file_url" }
    ]');
